services:
  consul:
    image: hashicorp/consul:latest
    container_name: ms-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - microservice-network

  mongodb:
    image: mongo:latest
    container_name: ms-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservice-network
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: ms-config-service
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=dev
      - RABBITMQ_URL=amqp://guest:guest@ms-rabbitmq:5672
    volumes:
      - ./config-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - microservice-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: ms-product-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=dev
      - CONFIG_SERVER_URL=http://ms-config-service:4000
      - RABBITMQ_URL=amqp://guest:guest@ms-rabbitmq:5672
    volumes:
      - ./product-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: ms-order-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=dev
      - CONFIG_SERVER_URL=http://ms-config-service:4000
    volumes:
      - ./order-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network
  
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: ms-customer-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=dev
      - CONFIG_SERVER_URL=http://ms-config-service:4000
    volumes:
      - ./customer-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network
  
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: ms-payment-service
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=dev
      - CONFIG_SERVER_URL=http://ms-config-service:4000
    volumes:
      - ./payment-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: ms-inventory-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=dev
      - CONFIG_SERVER_URL=http://ms-config-service:4000
    volumes:
      - ./inventory-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: ms-auth-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=dev
      - CONFIG_SERVER_URL=http://ms-config-service:4000
    volumes:
      - ./auth-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: ms-notification-service
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=dev
      - RABBITMQ_URL=amqp://guest:guest@ms-rabbitmq:5672
    volumes:
      - ./notification-service:/usr/src/app
    restart: unless-stopped
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservice-network
  loki:
    image: grafana/loki:latest
    container_name: ms-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - microservice-network

  grafana:
    image: grafana/grafana:latest
    container_name: ms-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - microservice-network
    depends_on:
      - payment-service
      - product-service
      - order-service
      - customer-service
      - inventory-service
      - auth-service
      - notification-service
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: ms-gateway-service
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api-gateway:/usr/src/app
    restart: unless-stopped
    depends_on:
      - config-service
      - product-service
      - order-service
      - customer-service
      - inventory-service
      - notification-service
    networks:
      - microservice-network
volumes:
  mongodb_data:
  rabbitmq_data:
  rabbitmq_logs:
  grafana-storage:

networks:
  microservice-network:
    driver: bridge
